Repository DisciplinaOU/disciplina, pull requests merged in 2018-10, with the labels that each got.

#270 [DSCP-287][DSCP-288] Educator API fixes
  educator/database/schema.sql
  educator/src/Dscp/DB/SQLite/Functions.hs
  educator/src/Dscp/DB/SQLite/Instances.hs
  educator/src/Dscp/DB/SQLite/Queries.hs
  educator/src/Dscp/Educator/Web/Bot/Setting.hs
  educator/src/Dscp/Educator/Web/Educator/API.hs
  educator/src/Dscp/Educator/Web/Educator/Handlers.hs
  educator/src/Dscp/Educator/Web/Educator/Types.hs
  educator/tests/Test/Dscp/DB/SQLite/Queries.hs
  educator/tests/Test/Dscp/Educator/Web/Educator/Queries.hs
  educator/tests/Test/Dscp/Educator/Web/Instances.hs
  educator/tests/Test/Dscp/Educator/Web/Student/Queries.hs
  specs/disciplina/educator/api/educator.yaml
Labels: critical

#290 [DSCP-256] Improve snowdrop-related errors
  core/src/Dscp/Core/Foundation/Witness.hs
  educator/src/Dscp/Educator/Web/Educator/Error.hs
  educator/src/Dscp/Educator/Web/Educator/Handlers.hs
  educator/src/Dscp/Educator/Web/Student/Error.hs
  educator/src/Dscp/Educator/Web/Student/Handlers.hs
  faucet/src/Dscp/Faucet/Web/Error.hs
  faucet/src/Dscp/Faucet/Web/Handlers.hs
  specs/disciplina/witness/api/witness.yaml
  witness/src/Dscp/Snowdrop/AccountValidation.hs
  witness/src/Dscp/Snowdrop/Configuration.hs
  witness/src/Dscp/Snowdrop/Expanders.hs
  witness/src/Dscp/Snowdrop/Instances.hs
  witness/src/Dscp/Snowdrop/Types.hs
  witness/src/Dscp/Web/Class.hs
  witness/src/Dscp/Witness/Logic/Exceptions.hs
  witness/src/Dscp/Witness/Web/Client/Error.hs
  witness/src/Dscp/Witness/Web/Error.hs
  witness/src/Dscp/Witness/Web/Logic.hs
  witness/src/Dscp/Witness/Web/Server.hs
  witness/src/Dscp/Witness/Web/Util.hs
  witness/tests/Test/Dscp/Witness/Tx/MoneyTxSpec.hs
  witness/tests/Test/Dscp/Witness/Tx/PublicationTxSpec.hs
Labels: breaks compatibility, release-0.2.0

#289 [DSCP-302] Add endpoint to get publications
  config.yaml
  core/package.yaml
  core/src/Dscp/Core/Aeson.hs
  core/src/Dscp/Core/Arbitrary.hs
  core/src/Dscp/Core/Foundation/Educator.hs
  core/src/Dscp/Core/Foundation/Instances.hs
  core/src/Dscp/Core/Foundation/Witness.hs
  core/src/Dscp/Crypto/Aeson.hs
  core/src/Dscp/Crypto/Arbitrary.hs
  core/src/Dscp/Util.hs
  core/src/Dscp/Util/Aeson.hs
  core/src/Dscp/Util/Test.hs
  core/tests/Test/Dscp/Core/Serialise.hs
  core/tests/Test/Dscp/Crypto/Serialise.hs
  docs/make-test-publication.md
  educator/src/Dscp/Educator/Workers.hs
  faucet/src/Dscp/Faucet/Web/Logic.hs
  scripts/launch/node.sh
  scripts/test/student-submissions-spam.sh
  specs/disciplina/witness/api/witness.yaml
  wallet/src/Dscp/Wallet/Backend.hs
  witness/package.yaml
  witness/src/Dscp/Resource/Keys/Types.hs
  witness/src/Dscp/Snowdrop/Configuration.hs
  witness/src/Dscp/Snowdrop/Expanders.hs
  witness/src/Dscp/Snowdrop/Instances.hs
  witness/src/Dscp/Snowdrop/Mode.hs
  witness/src/Dscp/Snowdrop/PublicationValidation.hs
  witness/src/Dscp/Snowdrop/Storage/Pure.hs
  witness/src/Dscp/Snowdrop/Storage/Types.hs
  witness/src/Dscp/Witness/Logic/Exceptions.hs
  witness/src/Dscp/Witness/Logic/Getters.hs
  witness/src/Dscp/Witness/Logic/Processing.hs
  witness/src/Dscp/Witness/Logic/Traversals.hs
  witness/src/Dscp/Witness/Logic/Tx.hs
  witness/src/Dscp/Witness/Mempool/Logic.hs
  witness/src/Dscp/Witness/Web.hs
  witness/src/Dscp/Witness/Web/API.hs
  witness/src/Dscp/Witness/Web/Arbitrary.hs
  witness/src/Dscp/Witness/Web/Client/Logic.hs
  witness/src/Dscp/Witness/Web/Handlers.hs
  witness/src/Dscp/Witness/Web/Logic.hs
  witness/src/Dscp/Witness/Web/Types.hs
  witness/tests/Test/Dscp/Witness/Common.hs
  witness/tests/Test/Dscp/Witness/Explorer/ExplorerSpec.hs
  witness/tests/Test/Dscp/Witness/Mode.hs
  witness/tests/Test/Dscp/Witness/SerialiseSpec.hs
  witness/tests/Test/Dscp/Witness/Tx/FeeSpec.hs
  witness/tests/Test/Dscp/Witness/Tx/MoneyTxSpec.hs
  witness/tests/Test/Dscp/Witness/Tx/PublicationTxSpec.hs
Labels: breaks compatibility

#293 [DSCP-264] Improvements in Educator API, step 2
  educator/src/Dscp/Educator/Web/Bot/Handlers.hs
  educator/src/Dscp/Educator/Web/Educator/API.hs
  educator/src/Dscp/Educator/Web/Educator/Handlers.hs
  educator/src/Dscp/Educator/Web/Educator/Queries.hs
  educator/src/Dscp/Educator/Web/Educator/Types.hs
  educator/src/Dscp/Educator/Web/Student/API.hs
  educator/src/Dscp/Educator/Web/Student/Handlers.hs
  educator/src/Dscp/Educator/Web/Student/Types.hs
  educator/src/Dscp/Educator/Web/Types.hs
  educator/tests/Test/Dscp/Educator/Bot/Endpoints.hs
  educator/tests/Test/Dscp/Educator/Web/Educator/Queries.hs
  specs/disciplina/educator/api/educator.yaml
  specs/disciplina/educator/api/student.yaml
Labels: wip
