Repository DisciplinaOU/disciplina, pull requests merged in 2019-02, with the labels that each got.

#360 [DSCP-438] Checkcv-PDF endpoint
  pdfs/README.md
  pdfs/app/Main.hs
  pdfs/package.yaml
  pdfs/src/Pdf/Scanner.hs
  pdfs/tests/Main.hs
  specs/disciplina/witness/api/witness.yaml
  stack.yaml
  witness/package.yaml
  witness/src/Dscp/Witness/Web/API.hs
  witness/src/Dscp/Witness/Web/Client/Logic.hs
  witness/src/Dscp/Witness/Web/Handlers.hs
  witness/src/Dscp/Witness/Web/Logic.hs
  witness/src/Dscp/Witness/Web/Types.hs
Labels: critical, wip

#367 [DSCP-446] FairCV PDF from LaTeX template
  core/src/Dscp/Core/Foundation/Educator.hs
  educator/src/Dscp/Educator/Web/Educator/Types.hs
  educator/src/Dscp/Educator/Web/Types.hs
  multi-educator/src/Dscp/MultiEducator/Web/Educator/Handlers.hs
  pdfs/inject/Main.hs
  pdfs/package.yaml
  pdfs/src/Pdf/FromLatex.hs
  pdfs/src/Pdf/MkLatex.hs
  pdfs/template/faircv.cls
  pdfs/template/fonts/ProximaNova/ProximaNova-Bold.otf
  pdfs/template/fonts/ProximaNova/ProximaNova-BoldItalic.otf
  pdfs/template/fonts/ProximaNova/ProximaNova-Regular.otf
  pdfs/template/fonts/ProximaNova/ProximaNova-RegularItalic.otf
  pdfs/template/images/degree-level.png
  pdfs/template/images/diploma.png
  pdfs/template/images/example-qr.png
  pdfs/template/images/header-background.jpg
  pdfs/template/images/major.png
  pdfs/template/images/minor.png
  pdfs/template/images/url.png
  pdfs/template/labels/en.tex
  pdfs/template/labels/ru.tex
  pdfs/test-pdf/Main.hs
  release.nix
  stack.yaml
  tools/src/faircv/Main.hs
Labels: wip

#386 [DSCP-475] Cert logic preparations
  core/src/Dscp/Crypto/Util.hs
  default.nix
  educator/src/Dscp/Educator/Web/Educator/Error.hs
  educator/src/Dscp/Educator/Web/Student/Error.hs
  pdfs/package.yaml
  pdfs/src/Pdf/FromLatex.hs
  scripts/test/client-api-ghci.sh
  stack.yaml
  tools/src/faircv/Main.hs
  tools/src/keygen/KeygenSecret.hs
Labels: critical
